### ISSUE TITLE
程序卡在了[o] 饼状图绘制中…… 

### ISSUE THREAD

**Issue by DHWxiao** [ljy1058318852/ExportReport#1]
作者您好，我在使用您这个工具的时候，程序一直卡在 [o] 饼状图绘制中……  过程，通过debug，我发现他一直卡在绘饼状图的一个方法这里，请问是什么原因导致的啊
![image](https://github.com/Potato-py/ExportReport/assets/23455365/2f973572-7f78-44bd-b4bf-8cc593e31622)
![image](https://github.com/Potato-py/ExportReport/assets/23455365/f11496cf-659e-49ca-b168-1dd2ae7f573c)

**Comment by DHWxiao** [comment]
网上搜了很多资料，最后成功解决，问题的原因是 kaleido 库不能安装最新版本，需要回退到 0.1.*， pip install --upgrade "kaleido==0.1.*"

**Comment by potato-security** [comment]
很抱歉很晚才看到你的消息，同时感谢你的踩坑，我想它会帮助到其他人
