### ISSUE TITLE
xray模块存在无法转换html问题

### ISSUE THREAD

**Issue by x1hy9** [ljy1058318852/ExportReport#2]
**html_xray.py**中的**format_xray_targets_data**函数中的`'目标描述': vuln_info['目标描述']`应改成风险描述

**Comment by ljy1058318852** [comment]
感谢你的issue，已更新git仓库

**Comment by potato-security** [comment]
x1hy9，感谢您提交的issue：

为满足主程序参数需求，故存在vuln_info['目标描述']
但xray原始报告中并不存在该字段，故该字段应采用`vuln_info['目标地址']`作为`vuln_info['目标描述']`
即'目标描述': vuln_info.get('目标描述', vuln_info['目标地址'])

已更新git仓库
